# Generated by Django 3.1 on 2021-01-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210116_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
